/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examen2manueldavidmontoya;

/**
 *
 * @author monto
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario1
     */
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vingresarencuesta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Bienvenidos a la encuesta");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 310, 70);

        vingresarencuesta.setBackground(new java.awt.Color(204, 255, 153));
        vingresarencuesta.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        vingresarencuesta.setForeground(new java.awt.Color(255, 153, 153));
        vingresarencuesta.setText("Ingresar a la Encuesta");
        vingresarencuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vingresarencuestaActionPerformed(evt);
            }
        });
        jPanel1.add(vingresarencuesta);
        vingresarencuesta.setBounds(190, 300, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\monto\\OneDrive\\Escritorio\\encuestas.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 20, 290, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 650, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vingresarencuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vingresarencuestaActionPerformed
       Formulario2 formulario2 = new Formulario2();
       formulario2.setSize(700, 850);
        formulario2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_vingresarencuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton vingresarencuesta;
    // End of variables declaration//GEN-END:variables
}
