/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examen2manueldavidmontoya;

import javax.swing.JOptionPane;

/**
 *
 * @author monto
 */
public class Formulario2 extends javax.swing.JFrame {
    private int contadorEncuestas = 1;
    private int contadorSi = 0;
    private int contadorNo = 0;
    /**
     * Creates new form Formulario2
     */
    public Formulario2() {
        initComponents();
        numencuesta.setText(String.valueOf(contadorEncuestas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vnombre = new javax.swing.JTextField();
        vedad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rsi = new javax.swing.JRadioButton();
        rno = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        bregistrar = new javax.swing.JButton();
        breporte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        vcorreo = new javax.swing.JTextField();
        numencuesta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        vnombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnombreActionPerformed(evt);
            }
        });
        getContentPane().add(vnombre);
        vnombre.setBounds(110, 30, 140, 22);

        vedad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(vedad);
        vedad.setBounds(360, 80, 40, 22);

        jLabel1.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Edad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 80, 60, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Carro Propio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 140, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("# Encuesta");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 20, 100, 25);

        rsi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rsi.setForeground(new java.awt.Color(0, 0, 255));
        rsi.setText("Si");
        rsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsiActionPerformed(evt);
            }
        });
        getContentPane().add(rsi);
        rsi.setBounds(260, 130, 50, 30);

        rno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rno.setForeground(new java.awt.Color(0, 0, 255));
        rno.setText("No");
        rno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnoActionPerformed(evt);
            }
        });
        getContentPane().add(rno);
        rno.setBounds(260, 170, 50, 30);

        jPanel1.setLayout(new java.awt.GridLayout());

        bregistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bregistrar.setForeground(new java.awt.Color(0, 0, 0));
        bregistrar.setText("Registrar");
        bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(bregistrar);

        breporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        breporte.setForeground(new java.awt.Color(0, 0, 0));
        breporte.setText("Reporte");
        breporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breporteActionPerformed(evt);
            }
        });
        jPanel1.add(breporte);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 230, 360, 100);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 70, 30);

        vcorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(vcorreo);
        vcorreo.setBounds(110, 80, 150, 22);

        numencuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numencuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numencuestaActionPerformed(evt);
            }
        });
        jPanel2.add(numencuesta);
        numencuesta.setBounds(440, 30, 80, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\monto\\OneDrive\\Escritorio\\EncuestaFormulario.jpg")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 0, 610, 550);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 590, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnombreActionPerformed

    private void numencuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numencuestaActionPerformed
        
    }//GEN-LAST:event_numencuestaActionPerformed

    private void breporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breporteActionPerformed
        Formulario3 formulario3 = new Formulario3();
       formulario3.setSize(700, 850);
        formulario3.setVisible(true);
        this.hide();
    }//GEN-LAST:event_breporteActionPerformed

    private void bregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrarActionPerformed
    
        //contadorEncuestas++;
       // numencuesta.setText(String.valueOf(contadorEncuestas));
        // Obtener los valores de los campos de texto
    String nombre = vnombre.getText();
    String correo = vcorreo.getText();
    //float edad = Float.parseFloat(vedad.getText());
    String edadStr = vedad.getText();
    // Validar que los campos no estén vacíos
    if(nombre.isEmpty() || correo.isEmpty() || edadStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        return;
    }
    
    int edad = 0;
    try {
        edad = Integer.parseInt(edadStr);
    } catch (NumberFormatException e) {
        // Si la edad no es un número válido, mostrar una alerta y salir del método
        JOptionPane.showMessageDialog(null, "La edad debe ser un número válido.");
        return;
    }

    // Comprobar si la edad está entre 18 y 50
    if (edad < 18 || edad > 50) {
        // Mostrar una alerta si la edad está fuera del rango permitido
        JOptionPane.showMessageDialog(null, "La edad debe estar entre 18 y 50 años.");
        return;
    }
    boolean tieneCarroPropio = rsi.isSelected();
    // Agregar los valores a la clase Encuestas
    Encuesta.agregarRegistro(nombre, correo, edad, contadorEncuestas, tieneCarroPropio);


    // Incrementar el contador de encuestas
    contadorEncuestas++;

    // Actualizar el valor del campo de texto numencuesta
    numencuesta.setText(String.valueOf(contadorEncuestas));
    // Limpiar los campos de texto
    vnombre.setText("");
    vcorreo.setText("");
    vedad.setText("");
    rsi.setSelected(false);
    rno.setSelected(false);
    }//GEN-LAST:event_bregistrarActionPerformed

    private void rsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rsiActionPerformed

    private void rnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnoActionPerformed
        // Incrementar el contador de "No"
    contadorNo++;
    
    // Obtener el texto actual del botón "No"
    String textoActual = rno.getText();
    
    // Agregar el contador al texto actual
    String nuevoTexto = textoActual + " (" + contadorNo + ")";
    
    // Establecer el nuevo texto en el botón "No"
    rno.setText(nuevoTexto);
    }//GEN-LAST:event_rnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bregistrar;
    private javax.swing.JButton breporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numencuesta;
    private javax.swing.JRadioButton rno;
    private javax.swing.JRadioButton rsi;
    private javax.swing.JTextField vcorreo;
    private javax.swing.JTextField vedad;
    private javax.swing.JTextField vnombre;
    // End of variables declaration//GEN-END:variables
}
